- name: "Generar informe HTML consolidado en localhost y moverlo a LNXADMUX01"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    tmp_json_dir: "/tmp/cve24813_reports"
    output_html: "/tmp/cve24813_report_{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}.html"
  tasks:
    - name: "Leer todos los JSONs generados"
      find:
        paths: "{{ tmp_json_dir }}"
        patterns: "report-*.json"
      register: found_reports

    - name: "Fallar si no hay reportes"
      fail:
        msg: "No se encontraron JSONs en {{ tmp_json_dir }}"
      when: found_reports.files | length == 0

    - name: "Cargar JSONs en lista"
      set_fact:
        reports_list: "{{ reports_list | default([]) + [ (lookup('file', item.path) | from_json ) ] }}"
      loop: "{{ found_reports.files }}"
      changed_when: false

    - name: "Construir resumen de hosts y evaluar vulnerabilidad"
      set_fact:
        summary_hosts_versions: "{{ summary_hosts_versions | default([]) + [ {
          'host': item.host,
          'tomcat_pkg_version_display': ((item.tomcat_pkg_version | default([]) | first) | default('unknown')),
          'catalina_raw': (item.catalina_version_raw | default('')),
          'vulnerability_status':
            (
              (
                (item.tomcat_pkg_version | default([]) | first | regex_search('9\\.0\\.(\\d+)', '\\1') | first | int) is defined and
                ((item.tomcat_pkg_version | first | regex_search('9\\.0\\.(\\d+)', '\\1') | first | int) <= 98)
              ) or
              (
                (item.tomcat_pkg_version | default([]) | first | regex_search('10\\.1\\.(\\d+)', '\\1') | first | int) is defined and
                ((item.tomcat_pkg_version | first | regex_search('10\\.1\\.(\\d+)', '\\1') | first | int) <= 34)
              ) or
              (
                (item.tomcat_pkg_version | default([]) | first | regex_search('11\\.0\\.(\\d+)', '\\1') | first | int) is defined and
                ((item.tomcat_pkg_version | first | regex_search('11\\.0\\.(\\d+)', '\\1') | first | int) <= 2)
              )
            )
            | ternary('Vulnerable', ((item.tomcat_pkg_version | first) is defined) | ternary('No vulnerable','Indeterminado'))
        } ] }}"
      loop: "{{ reports_list }}"
      loop_control:
        label: "{{ item.host }}"
      changed_when: false

    - name: "Generar HTML final"
      template:
        src: "templates/report.html.j2"
        dest: "{{ output_html }}"
        mode: '0644'
      vars:
        reports: "{{ reports_list }}"
        hosts_summary: "{{ summary_hosts_versions }}"

    - name: "Copiar reporte HTML al servidor LNXADMUX01"
      ansible.builtin.copy:
        src: "{{ output_html }}"
        dest: "/tmp/"
      delegate_to: LNXADMUX01

    - name: "Mostrar ubicación final"
      debug:
        msg: "✅ Reporte generado en {{ output_html }} y copiado a /tmp/ en LNXADMUX01"
