- name: "Generar informe HTML consolidado en nodo de control"
  hosts: LNXADMUX01
  gather_facts: false
  vars:
    tmp_json_dir: "/tmp/cve24813_reports"
    output_html: "/tmp/cve24813_report_{{ ansible_date_time.date }}.html"

  tasks:
    - name: "Leer todos los JSONs generados"
      delegate_to: LNXADMUX01
      run_once: true
      find:
        paths: "{{ tmp_json_dir }}"
        patterns: "report-*.json"
      register: found_reports

    - name: "Verificar que existan JSONs antes de procesar"
      delegate_to: LNXADMUX01
      run_once: true
      fail:
        msg: "No se encontraron reportes JSON en {{ tmp_json_dir }}. ¿Ejecutaste la fase de recolección?"
      when: found_reports.files | length == 0

    - name: "Cargar JSONs a variable (lista)"
      delegate_to: LNXADMUX01
      run_once: true
      set_fact:
        reports_list: "{{ reports_list | default([]) + [ (lookup('ansible.builtin.file', item.path) | from_json) ] }}"
      loop: "{{ found_reports.files | default([]) }}"
      changed_when: false

    - name: "Construir resumen de hosts y versiones Tomcat (con evaluación de vulnerabilidad)"
      delegate_to: LNXADMUX01
      run_once: true
      set_fact:
        summary_hosts_versions: "{{ summary_hosts_versions | default([]) + [ {
          'host': item.host,
          'tomcat_pkg_version_display': ((item.tomcat_pkg_version | default([]) | first) | default('unknown')),
          'catalina_raw': (item.catalina_version_raw | default('')),
          'vulnerability_status':
            (
              (
                (item.tomcat_pkg_version | default([]) | first | regex_search('9\\.0\\.(\\d+)', '\\1') | first | int) is defined and
                ((item.tomcat_pkg_version | first | regex_search('9\\.0\\.(\\d+)', '\\1') | first | int) <= 98)
              ) or
              (
                (item.tomcat_pkg_version | default([]) | first | regex_search('10\\.1\\.(\\d+)', '\\1') | first | int) is defined and
                ((item.tomcat_pkg_version | first | regex_search('10\\.1\\.(\\d+)', '\\1') | first | int) <= 34)
              ) or
              (
                (item.tomcat_pkg_version | default([]) | first | regex_search('11\\.0\\.(\\d+)', '\\1') | first | int) is defined and
                ((item.tomcat_pkg_version | first | regex_search('11\\.0\\.(\\d+)', '\\1') | first | int) <= 2)
              )
            )
            | ternary('Vulnerable', ((item.tomcat_pkg_version | first) is defined) | ternary('No vulnerable','Indeterminado'))
        } ] }}"
      loop: "{{ reports_list }}"
      loop_control:
        label: "{{ item.host }}"
      changed_when: false

    - name: "Generar HTML a partir de template"
      delegate_to: LNXADMUX01
      run_once: true
      template:
        src: "templates/report.html.j2"
        dest: "{{ output_html }}"
        mode: '0644'
      vars:
        reports: "{{ reports_list | default([]) }}"
        hosts_summary: "{{ summary_hosts_versions | default([]) }}"

    - name: "Notificar ubicación del informe"
      delegate_to: LNXADMUX01
      run_once: true
      debug:
        msg: "Informe HTML generado en {{ output_html }} (contiene {{ reports_list|length }} hosts)"
